# Processing Raw Conversion

This notebook converts the compressed eICU files from:
```
data/raw/eicu/*.csv.gz
```
into standard CSV files stored in:
```
data/processed/*.csv
```
It also checks the converted files, reads their column names, and summarizes their sizes.

### Import Required Libraries

In [1]:
from pathlib import Path
import gzip
import shutil

import pandas as pd
from tqdm.auto import tqdm
from IPython.display import display

#### Explanation :
- `Path` manages project folders and file paths.
- `gzip` opens compressed .csv.gz files.
- `shutil` copies the decompressed data into .csv files.
- `pandas` creates summary tables.
- `tqdm` shows progress while files are being processed.
- `display` presents DataFrames clearly inside the notebook

### Locate the Project Root Folder

In [2]:
def find_project_root(start_path):
    """
    Search upward from the current folder until the project root is found.

    The project root must contain:
    - data/
    - notebooks/
    """
    
    current_path = start_path.resolve()

    for folder in [current_path, *current_path.parents]:
        data_folder = folder / "data"
        notebooks_folder = folder / "notebooks"

        if data_folder.is_dir() and notebooks_folder.is_dir():
            return folder

    raise FileNotFoundError(
        "Project root could not be found. "
        "Make sure the project contains both data/ and notebooks/ folders."
    )


PROJECT_ROOT = find_project_root(Path.cwd())

print(f"Project root: {PROJECT_ROOT}")

Project root: C:\Users\samsa\Documents\Capstone Project\Project

#### Explanation :
The notebook is stored inside:
```
notebooks/module_1/
```
The function searches upward from the current working folder until it finds a folder containing both `data` and `notebooks`.

This is safer than using a fixed number of `.parent` operations because the notebook can work whether Jupyter starts from the project root, `notebooks`, or `notebooks/module_1`.

### Define the Raw and Processed Data Folders

In [3]:
RAW_DIR = PROJECT_ROOT / "data" / "raw" / "eicu"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

print("=" * 100)
print("PROJECT FOLDER PATHS")
print("=" * 100)
print(f"Project root     : {PROJECT_ROOT}")
print(f"Raw eICU folder  : {RAW_DIR}")
print(f"Processed folder : {PROCESSED_DIR}")
print("=" * 100)

====================================================================================================
PROJECT FOLDER PATHS
====================================================================================================
Project root     : C:\Users\samsa\Documents\Capstone Project\Project
Raw eICU folder  : C:\Users\samsa\Documents\Capstone Project\Project\data\raw\eicu
Processed folder : C:\Users\samsa\Documents\Capstone Project\Project\data\processed
====================================================================================================

#### Explanation :
The notebook uses the following folders:

- Raw compressed files: `data/raw/eicu/`
- Converted CSV files: `data/processed/`

Using `Path` keeps the code readable and works across Windows, macOS, and Linux.

### Check the Input Folder and Create the Output Folder

In [4]:
if not RAW_DIR.exists():
    raise FileNotFoundError(
        f"Raw eICU folder was not found:\n{RAW_DIR}"
    )

if not RAW_DIR.is_dir():
    raise NotADirectoryError(
        f"The raw eICU path is not a folder:\n{RAW_DIR}"
    )

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Raw eICU folder found.")
print("Processed folder is ready.")

Raw eICU folder found.
Processed folder is ready.

#### Explanation :
The code stops with a clear error if `data/raw/eicu/` does not exist.

The `data/processed/` folder is created automatically when needed. Existing folders and files are not deleted.

### Find All Compressed eICU Files

In [5]:
gz_files = sorted(RAW_DIR.glob("*.csv.gz"))

print(f"Total .csv.gz files found: {len(gz_files)}")

if len(gz_files) == 0:
    raise FileNotFoundError(
        f"No .csv.gz files were found inside:\n{RAW_DIR}"
    )

Total .csv.gz files found: 31

#### Explanation :
This code searches the raw eICU folder for files ending in `.csv.gz`.

The files are sorted by name so that they are processed in a consistent order.

### Display the Raw File Names

In [6]:
print("=" * 100)
print("RAW eICU FILES")
print("=" * 100)

for file_number, gz_file in enumerate(gz_files, start=1):
    print(f"{file_number:02d}. {gz_file.name}")

====================================================================================================
RAW eICU FILES
====================================================================================================
01. admissionDrug.csv.gz
02. admissionDx.csv.gz
03. allergy.csv.gz
04. apacheApsVar.csv.gz
05. apachePatientResult.csv.gz
06. apachePredVar.csv.gz
07. carePlanCareProvider.csv.gz
08. carePlanEOL.csv.gz
09. carePlanGeneral.csv.gz
10. carePlanGoal.csv.gz
11. carePlanInfectiousDisease.csv.gz
12. customLab.csv.gz
13. diagnosis.csv.gz
14. hospital.csv.gz
15. infusionDrug.csv.gz
16. intakeOutput.csv.gz
17. lab.csv.gz
18. medication.csv.gz
19. microLab.csv.gz
20. note.csv.gz
21. nurseAssessment.csv.gz
22. nurseCare.csv.gz
23. nurseCharting.csv.gz
24. pastHistory.csv.gz
25. patient.csv.gz
26. physicalExam.csv.gz
27. respiratoryCare.csv.gz
28. respiratoryCharting.csv.gz
29. treatment.csv.gz
30. vitalAperiodic.csv.gz
31. vitalPeriodic.csv.gz

#### Explanation :
This cell displays every compressed eICU table before conversion.

It helps confirm that files such as `patient.csv.gz`, `lab.csv.gz`, and `vitalPeriodic.csv.gz` are available.

### Choose Whether Existing CSV Files Should Be Replaced

In [7]:
OVERWRITE_EXISTING = False

print(f"Overwrite existing CSV files: {OVERWRITE_EXISTING}")

Overwrite existing CSV files: False

#### Explanation :
When `OVERWRITE_EXISTING` is `False`, an existing processed CSV file is skipped.

Set it to `True` only when all processed files should be recreated from the compressed raw files.

### Convert the Compressed Files into CSV Files

In [8]:
conversion_records = []

for gz_file in tqdm(
    gz_files,
    desc="Converting eICU files",
    unit="file"
):
    # admissionDrug.csv.gz becomes admissionDrug.csv
    csv_file = PROCESSED_DIR / gz_file.with_suffix("").name

    # Temporary file prevents an incomplete CSV from replacing a valid file
    temporary_file = csv_file.with_suffix(".csv.tmp")

    status = ""
    error_message = ""

    try:
        if csv_file.exists() and not OVERWRITE_EXISTING:
            status = "Skipped"

        else:
            # Remove an old temporary file if one exists
            if temporary_file.exists():
                temporary_file.unlink()

            # Decompress the source file into the temporary CSV file
            with gzip.open(gz_file, "rb") as compressed_file:
                with open(temporary_file, "wb") as output_file:
                    shutil.copyfileobj(compressed_file, output_file)

            # Replace the final CSV only after conversion succeeds
            temporary_file.replace(csv_file)

            status = "Converted"

    except Exception as error:
        status = "Failed"
        error_message = str(error)

        # Remove an incomplete temporary file
        if temporary_file.exists():
            temporary_file.unlink()

    conversion_records.append({
        "raw_file": gz_file.name,
        "processed_file": csv_file.name,
        "status": status,
        "error": error_message
    })

Converting eICU files:   0%|          | 0/31 [00:00<?, ?file/s]

#### Explanation :
Each `.csv.gz` file is decompressed and saved as a regular `.csv` file.

For example:
```
data/raw/eicu/patient.csv.gz
```
becomes:
```
data/processed/patient.csv
```
The data is copied in smaller blocks instead of loading the entire table into memory. This is important because some eICU tables are very large.

A temporary file is used during conversion. The final CSV is created only after the decompression finishes successfully.

### Review the Conversion Results

In [9]:
conversion_summary_df = pd.DataFrame(conversion_records)

display(conversion_summary_df)

,raw_file,processed_file,status,error
0,admissionDrug.csv.gz,admissionDrug.csv,Converted,
1,admissionDx.csv.gz,admissionDx.csv,Converted,
2,allergy.csv.gz,allergy.csv,Converted,
3,apacheApsVar.csv.gz,apacheApsVar.csv,Converted,
4,apachePatientResult.csv.gz,apachePatientResult.csv,Converted,
5,apachePredVar.csv.gz,apachePredVar.csv,Converted,
6,carePlanCareProvider.csv.gz,carePlanCareProvider.csv,Converted,
7,carePlanEOL.csv.gz,carePlanEOL.csv,Converted,
8,carePlanGeneral.csv.gz,carePlanGeneral.csv,Converted,
9,carePlanGoal.csv.gz,carePlanGoal.csv,Converted,
10,carePlanInfectiousDisease.csv.gz,carePlanInfectiousDisease.csv,Converted,
11,customLab.csv.gz,customLab.csv,Converted,
12,diagnosis.csv.gz,diagnosis.csv,Converted,
13,hospital.csv.gz,hospital.csv,Converted,
14,infusionDrug.csv.gz,infusionDrug.csv,Converted,
15,intakeOutput.csv.gz,intakeOutput.csv,Converted,
16,lab.csv.gz,lab.csv,Converted,
17,medication.csv.gz,medication.csv,Converted,
18,microLab.csv.gz,microLab.csv,Converted,
19,note.csv.gz,note.csv,Converted,
20,nurseAssessment.csv.gz,nurseAssessment.csv,Converted,
21,nurseCare.csv.gz,nurseCare.csv,Converted,
22,nurseCharting.csv.gz,nurseCharting.csv,Converted,
23,pastHistory.csv.gz,pastHistory.csv,Converted,
24,patient.csv.gz,patient.csv,Converted,
25,physicalExam.csv.gz,physicalExam.csv,Converted,
26,respiratoryCare.csv.gz,respiratoryCare.csv,Converted,
27,respiratoryCharting.csv.gz,respiratoryCharting.csv,Converted,
28,treatment.csv.gz,treatment.csv,Converted,
29,vitalAperiodic.csv.gz,vitalAperiodic.csv,Converted,
30,vitalPeriodic.csv.gz,vitalPeriodic.csv,Converted,

#### Explanation :
The summary table shows the result for every raw file:

- `Converted`: the CSV file was created.
- `Skipped`: the CSV file already existed.
- `Failed`: an error occurred during conversion.

The `error` column contains the error message when a conversion fails.

### Count Coverted, Skipped and Failed Files

In [10]:
converted_count = (
    conversion_summary_df["status"] == "Converted"
).sum()

skipped_count = (
    conversion_summary_df["status"] == "Skipped"
).sum()

failed_count = (
    conversion_summary_df["status"] == "Failed"
).sum()

print("=" * 70)
print("CONVERSION SUMMARY")
print("=" * 70)
print(f"Raw files found : {len(gz_files)}")
print(f"Files converted : {converted_count}")
print(f"Files skipped   : {skipped_count}")
print(f"Files failed    : {failed_count}")
print("=" * 70)

======================================================================
CONVERSION SUMMARY
======================================================================
Raw files found : 31
Files converted : 31
Files skipped   : 0
Files failed    : 0
======================================================================

#### Explanation :
This cell gives a simple count of the conversion results.

Skipped files are not errors. They mean that the processed CSV files were already available and `OVERWRITE_EXISTING` was set to `False`.

### Display Failed Conversions

In [11]:
failed_files_df = conversion_summary_df[
    conversion_summary_df["status"] == "Failed"
].copy()

if failed_files_df.empty:
    print("No conversion failures were found.")
else:
    print("The following files could not be converted:")
    display(failed_files_df)

No conversion failures were found.

#### Explanation :
Only failed conversions are displayed in this section.

This makes it easier to identify a damaged compressed file, permission problem, or storage issue.

### Find All Processed CSV Files

In [12]:
csv_files = sorted(PROCESSED_DIR.glob("*.csv"))

print(f"Total CSV files in data/processed: {len(csv_files)}")

if len(csv_files) == 0:
    raise FileNotFoundError(
        f"No CSV files were found inside:\n{PROCESSED_DIR}"
    )

Total CSV files in data/processed: 31

#### Explanation :
After conversion, the code searches `data/processed/` for all CSV files.

These files are used in the remaining validation and summary steps.

### Verify That Every Raw File Has a Processed CSV File

In [13]:
expected_csv_names = {
    gz_file.with_suffix("").name
    for gz_file in gz_files
}

processed_csv_names = {
    csv_file.name
    for csv_file in csv_files
}

missing_csv_files = sorted(
    expected_csv_names - processed_csv_names
)

additional_csv_files = sorted(
    processed_csv_names - expected_csv_names
)

print("=" * 100)
print("FILE MATCHING CHECK")
print("=" * 100)
print(f"Expected CSV files   : {len(expected_csv_names)}")
print(f"Processed CSV files  : {len(processed_csv_names)}")
print(f"Missing CSV files    : {len(missing_csv_files)}")
print(f"Additional CSV files : {len(additional_csv_files)}")
print("=" * 100)

====================================================================================================
FILE MATCHING CHECK
====================================================================================================
Expected CSV files   : 31
Processed CSV files  : 31
Missing CSV files    : 0
Additional CSV files : 0
====================================================================================================

#### Explanation :
The expected CSV names are created from the raw file names.

For example:
```
lab.csv.gz → lab.csv
```
The code compares the expected names with the files found in `data/processed/`.

An additional file is not necessarily a problem. It may be a CSV that was placed in the processed folder separately.

### Display Missing Processed Files

In [14]:
if missing_csv_files:
    print("Raw files without matching processed CSV files:")

    for file_name in missing_csv_files:
        print(f"- {file_name}")
else:
    print("Every raw .csv.gz file has a matching processed CSV file.")

Every raw .csv.gz file has a matching processed CSV file.

#### Explanation :
This cell identifies compressed files that do not have a matching CSV file.

A missing file may indicate that its conversion failed or that the notebook stopped before conversion finished.

### Display Additional Processed Files

In [15]:
if additional_csv_files:
    print("Additional CSV files found in data/processed:")

    for file_name in additional_csv_files:
        print(f"- {file_name}")
else:
    print("No additional CSV files were found.")

No additional CSV files were found.

#### Explanation :
This section displays CSV files that are present in `data/processed/` but do not have a matching `.csv.gz` file in `data/raw/eicu/`.

The notebook does not delete or modify these additional files.

### Read the Column Names from Every Processed Table

In [16]:
file_column_summary = []
column_read_errors = []

for csv_file in tqdm(
    csv_files,
    desc="Reading table headers",
    unit="file"
):
    try:
        # Read only the header, not the full table
        header_df = pd.read_csv(
            csv_file,
            nrows=0,
            low_memory=False
        )

        column_names = header_df.columns.tolist()

        file_column_summary.append({
            "file_name": csv_file.name,
            "total_columns": len(column_names),
            "column_names": column_names
        })

    except Exception as error:
        column_read_errors.append({
            "file_name": csv_file.name,
            "error": str(error)
        })

Reading table headers:   0%|          | 0/31 [00:00<?, ?file/s]

#### Explanation :
Only the header row of each CSV file is read.

This provides the column names without loading millions of patient records into memory. It is safer and faster for large eICU tables.

Any table that cannot be read is stored in a separate error list.

### Create the Column Summary Table

In [17]:
column_summary_df = pd.DataFrame(file_column_summary)

if not column_summary_df.empty:
    column_summary_df = column_summary_df.sort_values(
        by="file_name"
    ).reset_index(drop=True)

display(column_summary_df)

,file_name,total_columns,column_names
0,admissionDrug.csv,14,"[admissiondrugid, patientunitstayid, drugoffse..."
1,admissionDx.csv,6,"[admissiondxid, patientunitstayid, admitdxente..."
2,allergy.csv,13,"[allergyid, patientunitstayid, allergyoffset, ..."
3,apacheApsVar.csv,26,"[apacheapsvarid, patientunitstayid, intubated,..."
4,apachePatientResult.csv,23,"[apachepatientresultsid, patientunitstayid, ph..."
5,apachePredVar.csv,51,"[apachepredvarid, patientunitstayid, sicuday, ..."
6,carePlanCareProvider.csv,8,"[cplcareprovderid, patientunitstayid, careprov..."
7,carePlanEOL.csv,5,"[cpleolid, patientunitstayid, cpleolsaveoffset..."
8,carePlanGeneral.csv,6,"[cplgeneralid, patientunitstayid, activeupondi..."
9,carePlanGoal.csv,7,"[cplgoalid, patientunitstayid, cplgoaloffset, ..."
10,carePlanInfectiousDisease.csv,8,"[cplinfectid, patientunitstayid, activeupondis..."
11,customLab.csv,7,"[customlabid, patientunitstayid, labotheroffse..."
12,diagnosis.csv,7,"[diagnosisid, patientunitstayid, activeupondis..."
13,hospital.csv,4,"[hospitalid, numbedscategory, teachingstatus, ..."
14,infusionDrug.csv,9,"[infusiondrugid, patientunitstayid, infusionof..."
15,intakeOutput.csv,12,"[intakeoutputid, patientunitstayid, intakeoutp..."
16,lab.csv,10,"[labid, patientunitstayid, labresultoffset, la..."
17,medication.csv,15,"[medicationid, patientunitstayid, drugorderoff..."
18,microLab.csv,7,"[microlabid, patientunitstayid, culturetakenof..."
19,note.csv,8,"[noteid, patientunitstayid, noteoffset, noteen..."
20,nurseAssessment.csv,8,"[nurseassessid, patientunitstayid, nurseassess..."
21,nurseCare.csv,8,"[nursecareid, patientunitstayid, celllabel, nu..."
22,nurseCharting.csv,8,"[nursingchartid, patientunitstayid, nursingcha..."
23,pastHistory.csv,8,"[pasthistoryid, patientunitstayid, pasthistory..."
24,patient.csv,29,"[patientunitstayid, patienthealthsystemstayid,..."
25,physicalExam.csv,6,"[physicalexamid, patientunitstayid, physicalex..."
26,respiratoryCare.csv,34,"[respcareid, patientunitstayid, respcarestatus..."
27,respiratoryCharting.csv,7,"[respchartid, patientunitstayid, respchartoffs..."
28,treatment.csv,5,"[treatmentid, patientunitstayid, treatmentoffs..."
29,vitalAperiodic.csv,13,"[vitalaperiodicid, patientunitstayid, observat..."
30,vitalPeriodic.csv,19,"[vitalperiodicid, patientunitstayid, observati..."

#### Explanation :
The summary contains:

- The table filename
- The number of columns
- The complete list of column names

This gives a quick overview of the structure of every processed eICU table.

### Display Out the File Name and Column Count

In [18]:
if not column_summary_df.empty:
    display(
        column_summary_df[
            ["file_name", "total_columns"]
        ]
    )
else:
    print("No column information is available.")

                        file_name  total_columns
0               admissionDrug.csv             14
1                 admissionDx.csv              6
2                     allergy.csv             13
3                apacheApsVar.csv             26
4         apachePatientResult.csv             23
5               apachePredVar.csv             51
6        carePlanCareProvider.csv              8
7                 carePlanEOL.csv              5
8             carePlanGeneral.csv              6
9                carePlanGoal.csv              7
10  carePlanInfectiousDisease.csv              8
11                  customLab.csv              7
12                  diagnosis.csv              7
13                   hospital.csv              4
14               infusionDrug.csv              9
15               intakeOutput.csv             12
16                        lab.csv             10
17                 medication.csv             15
18                   microLab.csv              7
19                       note.csv              8
20            nurseAssessment.csv              8
21                  nurseCare.csv              8
22              nurseCharting.csv              8
23                pastHistory.csv              8
24                    patient.csv             29
25               physicalExam.csv              6
26            respiratoryCare.csv             34
27        respiratoryCharting.csv              7
28                  treatment.csv              5
29             vitalAperiodic.csv             13
30              vitalPeriodic.csv             19

#### Explanation :
This is a shorter version of the column summary.

It is useful when only the number of variables in each eICU table is needed.

#### Display the Columns of Each Table Clearly

In [19]:
for table_information in file_column_summary:
    print("=" * 100)
    print(f"File: {table_information['file_name']}")
    print(f"Total columns: {table_information['total_columns']}")
    print("-" * 100)

    for column_number, column_name in enumerate(
        table_information["column_names"],
        start=1
    ):
        print(f"{column_number:02d}. {column_name}")

    print()

====================================================================================================
File: admissionDrug.csv
Total columns: 14
----------------------------------------------------------------------------------------------------
01. admissiondrugid
02. patientunitstayid
03. drugoffset
04. drugenteredoffset
05. drugnotetype
06. specialtytype
07. usertype
08. rxincluded
09. writtenineicu
10. drugname
11. drugdosage
12. drugunit
13. drugadmitfrequency
14. drughiclseqno

====================================================================================================
File: admissionDx.csv
Total columns: 6
----------------------------------------------------------------------------------------------------
01. admissiondxid
02. patientunitstayid
03. admitdxenteredoffset
04. admitdxpath
05. admitdxname
06. admitdxtext

====================================================================================================
File: allergy.csv
Total columns: 13
----------------------------------------------------------------------------------------------------
01. allergyid
02. patientunitstayid
03. allergyoffset
04. allergyenteredoffset
05. allergynotetype
06. specialtytype
07. usertype
08. rxincluded
09. writtenineicu
10. drugname
11. allergytype
12. allergyname
13. drughiclseqno

====================================================================================================
File: apacheApsVar.csv
Total columns: 26
----------------------------------------------------------------------------------------------------
01. apacheapsvarid
02. patientunitstayid
03. intubated
04. vent
05. dialysis
06. eyes
07. motor
08. verbal
09. meds
10. urine
11. wbc
12. temperature
13. respiratoryrate
14. sodium
15. heartrate
16. meanbp
17. ph
18. hematocrit
19. creatinine
20. albumin
21. pao2
22. pco2
23. bun
24. glucose
25. bilirubin
26. fio2

====================================================================================================
File: apachePatientResult.csv
Total columns: 23
----------------------------------------------------------------------------------------------------
01. apachepatientresultsid
02. patientunitstayid
03. physicianspeciality
04. physicianinterventioncategory
05. acutephysiologyscore
06. apachescore
07. apacheversion
08. predictedicumortality
09. actualicumortality
10. predictediculos
11. actualiculos
12. predictedhospitalmortality
13. actualhospitalmortality
14. predictedhospitallos
15. actualhospitallos
16. preopmi
17. preopcardiaccath
18. ptcawithin24h
19. unabridgedunitlos
20. unabridgedhosplos
21. actualventdays
22. predventdays
23. unabridgedactualventdays

====================================================================================================
File: apachePredVar.csv
Total columns: 51
----------------------------------------------------------------------------------------------------
01. apachepredvarid
02. patientunitstayid
03. sicuday
04. saps3day1
05. saps3today
06. saps3yesterday
07. gender
08. teachtype
09. region
10. bedcount
11. admitsource
12. graftcount
13. meds
14. verbal
15. motor
16. eyes
17. age
18. admitdiagnosis
19. thrombolytics
20. diedinhospital
21. aids
22. hepaticfailure
23. lymphoma
24. metastaticcancer
25. leukemia
26. immunosuppression
27. cirrhosis
28. electivesurgery
29. activetx
30. readmit
31. ima
32. midur
33. ventday1
34. oobventday1
35. oobintubday1
36. diabetes
37. managementsystem
38. var03hspxlos
39. pao2
40. fio2
41. ejectfx
42. creatinine
43. dischargelocation
44. visitnumber
45. amilocation
46. day1meds
47. day1verbal
48. day1motor
49. day1eyes
50. day1pao2
51. day1fio2

====================================================================================================
File: carePlanCareProvider.csv
Total columns: 8
----------------------------------------------------------------------------------------------------
01. cplcareprovderid
02. patientunitstayid
03. careprovidersaveoffset
04. providertype
05. specialty
06. interventioncategory
07. managingphysician
08. activeupondischarge

====================================================================================================
File: carePlanEOL.csv
Total columns: 5
----------------------------------------------------------------------------------------------------
01. cpleolid
02. patientunitstayid
03. cpleolsaveoffset
04. cpleoldiscussionoffset
05. activeupondischarge

====================================================================================================
File: carePlanGeneral.csv
Total columns: 6
----------------------------------------------------------------------------------------------------
01. cplgeneralid
02. patientunitstayid
03. activeupondischarge
04. cplitemoffset
05. cplgroup
06. cplitemvalue

====================================================================================================
File: carePlanGoal.csv
Total columns: 7
----------------------------------------------------------------------------------------------------
01. cplgoalid
02. patientunitstayid
03. cplgoaloffset
04. cplgoalcategory
05. cplgoalvalue
06. cplgoalstatus
07. activeupondischarge

====================================================================================================
File: carePlanInfectiousDisease.csv
Total columns: 8
----------------------------------------------------------------------------------------------------
01. cplinfectid
02. patientunitstayid
03. activeupondischarge
04. cplinfectdiseaseoffset
05. infectdiseasesite
06. infectdiseaseassessment
07. responsetotherapy
08. treatment

====================================================================================================
File: customLab.csv
Total columns: 7
----------------------------------------------------------------------------------------------------
01. customlabid
02. patientunitstayid
03. labotheroffset
04. labothertypeid
05. labothername
06. labotherresult
07. labothervaluetext

====================================================================================================
File: diagnosis.csv
Total columns: 7
----------------------------------------------------------------------------------------------------
01. diagnosisid
02. patientunitstayid
03. activeupondischarge
04. diagnosisoffset
05. diagnosisstring
06. icd9code
07. diagnosispriority

====================================================================================================
File: hospital.csv
Total columns: 4
----------------------------------------------------------------------------------------------------
01. hospitalid
02. numbedscategory
03. teachingstatus
04. region

====================================================================================================
File: infusionDrug.csv
Total columns: 9
----------------------------------------------------------------------------------------------------
01. infusiondrugid
02. patientunitstayid
03. infusionoffset
04. drugname
05. drugrate
06. infusionrate
07. drugamount
08. volumeoffluid
09. patientweight

====================================================================================================
File: intakeOutput.csv
Total columns: 12
----------------------------------------------------------------------------------------------------
01. intakeoutputid
02. patientunitstayid
03. intakeoutputoffset
04. intaketotal
05. outputtotal
06. dialysistotal
07. nettotal
08. intakeoutputentryoffset
09. cellpath
10. celllabel
11. cellvaluenumeric
12. cellvaluetext

====================================================================================================
File: lab.csv
Total columns: 10
----------------------------------------------------------------------------------------------------
01. labid
02. patientunitstayid
03. labresultoffset
04. labtypeid
05. labname
06. labresult
07. labresulttext
08. labmeasurenamesystem
09. labmeasurenameinterface
10. labresultrevisedoffset

====================================================================================================
File: medication.csv
Total columns: 15
----------------------------------------------------------------------------------------------------
01. medicationid
02. patientunitstayid
03. drugorderoffset
04. drugstartoffset
05. drugivadmixture
06. drugordercancelled
07. drugname
08. drughiclseqno
09. dosage
10. routeadmin
11. frequency
12. loadingdose
13. prn
14. drugstopoffset
15. gtc

====================================================================================================
File: microLab.csv
Total columns: 7
----------------------------------------------------------------------------------------------------
01. microlabid
02. patientunitstayid
03. culturetakenoffset
04. culturesite
05. organism
06. antibiotic
07. sensitivitylevel

====================================================================================================
File: note.csv
Total columns: 8
----------------------------------------------------------------------------------------------------
01. noteid
02. patientunitstayid
03. noteoffset
04. noteenteredoffset
05. notetype
06. notepath
07. notevalue
08. notetext

====================================================================================================
File: nurseAssessment.csv
Total columns: 8
----------------------------------------------------------------------------------------------------
01. nurseassessid
02. patientunitstayid
03. nurseassessoffset
04. nurseassessentryoffset
05. cellattributepath
06. celllabel
07. cellattribute
08. cellattributevalue

====================================================================================================
File: nurseCare.csv
Total columns: 8
----------------------------------------------------------------------------------------------------
01. nursecareid
02. patientunitstayid
03. celllabel
04. nursecareoffset
05. nursecareentryoffset
06. cellattributepath
07. cellattribute
08. cellattributevalue

====================================================================================================
File: nurseCharting.csv
Total columns: 8
----------------------------------------------------------------------------------------------------
01. nursingchartid
02. patientunitstayid
03. nursingchartoffset
04. nursingchartentryoffset
05. nursingchartcelltypecat
06. nursingchartcelltypevallabel
07. nursingchartcelltypevalname
08. nursingchartvalue

====================================================================================================
File: pastHistory.csv
Total columns: 8
----------------------------------------------------------------------------------------------------
01. pasthistoryid
02. patientunitstayid
03. pasthistoryoffset
04. pasthistoryenteredoffset
05. pasthistorynotetype
06. pasthistorypath
07. pasthistoryvalue
08. pasthistoryvaluetext

====================================================================================================
File: patient.csv
Total columns: 29
----------------------------------------------------------------------------------------------------
01. patientunitstayid
02. patienthealthsystemstayid
03. gender
04. age
05. ethnicity
06. hospitalid
07. wardid
08. apacheadmissiondx
09. admissionheight
10. hospitaladmittime24
11. hospitaladmitoffset
12. hospitaladmitsource
13. hospitaldischargeyear
14. hospitaldischargetime24
15. hospitaldischargeoffset
16. hospitaldischargelocation
17. hospitaldischargestatus
18. unittype
19. unitadmittime24
20. unitadmitsource
21. unitvisitnumber
22. unitstaytype
23. admissionweight
24. dischargeweight
25. unitdischargetime24
26. unitdischargeoffset
27. unitdischargelocation
28. unitdischargestatus
29. uniquepid

====================================================================================================
File: physicalExam.csv
Total columns: 6
----------------------------------------------------------------------------------------------------
01. physicalexamid
02. patientunitstayid
03. physicalexamoffset
04. physicalexampath
05. physicalexamvalue
06. physicalexamtext

====================================================================================================
File: respiratoryCare.csv
Total columns: 34
----------------------------------------------------------------------------------------------------
01. respcareid
02. patientunitstayid
03. respcarestatusoffset
04. currenthistoryseqnum
05. airwaytype
06. airwaysize
07. airwayposition
08. cuffpressure
09. ventstartoffset
10. ventendoffset
11. priorventstartoffset
12. priorventendoffset
13. apneaparms
14. lowexhmvlimit
15. hiexhmvlimit
16. lowexhtvlimit
17. hipeakpreslimit
18. lowpeakpreslimit
19. hirespratelimit
20. lowrespratelimit
21. sighpreslimit
22. lowironoxlimit
23. highironoxlimit
24. meanairwaypreslimit
25. peeplimit
26. cpaplimit
27. setapneainterval
28. setapneatv
29. setapneaippeephigh
30. setapnearr
31. setapneapeakflow
32. setapneainsptime
33. setapneaie
34. setapneafio2

====================================================================================================
File: respiratoryCharting.csv
Total columns: 7
----------------------------------------------------------------------------------------------------
01. respchartid
02. patientunitstayid
03. respchartoffset
04. respchartentryoffset
05. respcharttypecat
06. respchartvaluelabel
07. respchartvalue

====================================================================================================
File: treatment.csv
Total columns: 5
----------------------------------------------------------------------------------------------------
01. treatmentid
02. patientunitstayid
03. treatmentoffset
04. treatmentstring
05. activeupondischarge

====================================================================================================
File: vitalAperiodic.csv
Total columns: 13
----------------------------------------------------------------------------------------------------
01. vitalaperiodicid
02. patientunitstayid
03. observationoffset
04. noninvasivesystolic
05. noninvasivediastolic
06. noninvasivemean
07. paop
08. cardiacoutput
09. cardiacinput
10. svr
11. svri
12. pvr
13. pvri

====================================================================================================
File: vitalPeriodic.csv
Total columns: 19
----------------------------------------------------------------------------------------------------
01. vitalperiodicid
02. patientunitstayid
03. observationoffset
04. temperature
05. sao2
06. heartrate
07. respiration
08. cvp
09. etco2
10. systemicsystolic
11. systemicdiastolic
12. systemicmean
13. pasystolic
14. padiastolic
15. pamean
16. st1
17. st2
18. st3
19. icp

#### Explanation :
This cell displays each table separately and numbers its columns.

The output is easier to read than showing every column list inside one large DataFrame.

### Display Tables That Could Not Be Read

In [20]:
column_error_df = pd.DataFrame(column_read_errors)

if column_error_df.empty:
    print("The headers of all processed CSV files were read successfully.")
else:
    print("The following CSV headers could not be read:")
    display(column_error_df)

The headers of all processed CSV files were read successfully.

#### Explanation :
This section checks whether every processed file has a readable CSV header.

A failure may indicate that a file is incomplete, damaged, empty, or not formatted as a valid CSV file.

### Calculate the Size of Every Processed File

In [21]:
file_size_summary = []

for csv_file in tqdm(
    csv_files,
    desc="Checking processed file sizes",
    unit="file"
):
    file_size_bytes = csv_file.stat().st_size
    file_size_mb = file_size_bytes / (1024 ** 2)
    file_size_gb = file_size_bytes / (1024 ** 3)

    file_size_summary.append({
        "file_name": csv_file.name,
        "file_path": str(csv_file),
        "size_bytes": file_size_bytes,
        "size_mb": round(file_size_mb, 2),
        "size_gb": round(file_size_gb, 4)
    })

Checking processed file sizes:   0%|          | 0/31 [00:00<?, ?file/s]

#### Explaination

The code measures each processed file in:

- Bytes
- Megabytes
- Gigabytes

This helps identify the largest eICU tables before later data cleaning and clustering work.

### Create the File Size Summary Table

In [23]:
file_size_summary_df = pd.DataFrame(file_size_summary)

file_size_summary_df = file_size_summary_df.sort_values(
    by="file_name"
).reset_index(drop=True)

display(file_size_summary_df)

,file_name,file_path,size_bytes,size_mb,size_gb
0,admissionDrug.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,311224613,296.81,0.2899
1,admissionDx.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,92417055,88.14,0.0861
2,allergy.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,125620366,119.80,0.1170
3,apacheApsVar.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,15843531,15.11,0.0148
4,apachePatientResult.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,51729916,49.33,0.0482
5,apachePredVar.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,22305326,21.27,0.0208
6,carePlanCareProvider.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,27866190,26.58,0.0260
7,carePlanEOL.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,38864,0.04,0.0000
8,carePlanGeneral.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,186123017,177.50,0.1733
9,carePlanGoal.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,37362797,35.63,0.0348
10,carePlanInfectiousDisease.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,490056,0.47,0.0005
11,customLab.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,77136,0.07,0.0001
12,diagnosis.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,283370401,270.24,0.2639
13,hospital.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,3943,0.00,0.0000
14,infusionDrug.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,278645140,265.74,0.2595
15,intakeOutput.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,1943916035,1853.86,1.8104
16,lab.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,2364239214,2254.71,2.2019
17,medication.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,632960518,603.64,0.5895
18,microLab.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,1171907,1.12,0.0011
19,note.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,321384743,306.50,0.2993
20,nurseAssessment.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,2339942226,2231.54,2.1792
21,nurseCare.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,1184161954,1129.30,1.1028
22,nurseCharting.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,11466038363,10934.87,10.6786
23,pastHistory.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,203629776,194.20,0.1896
24,patient.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,48277161,46.04,0.0450
25,physicalExam.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,1367111148,1303.78,1.2732
26,respiratoryCare.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,81131891,77.37,0.0756
27,respiratoryCharting.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,1230466869,1173.46,1.1460
28,treatment.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,338269723,322.60,0.3150
29,vitalAperiodic.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,981901126,936.41,0.9145
30,vitalPeriodic.csv,C:\Users\samsa\Documents\Capstone Project\Proj...,7938281236,7570.53,7.3931

#### Explanation :

This table provides the location and storage size of every processed CSV file.

The files are initially arranged alphabetically.

### Display Files from Largest to Smallest

In [24]:
largest_files_df = file_size_summary_df.sort_values(
    by="size_bytes",
    ascending=False
).reset_index(drop=True)

display(
    largest_files_df[
        ["file_name", "size_mb", "size_gb"]
    ]
)

                        file_name   size_mb  size_gb
0               nurseCharting.csv  10934.87  10.6786
1               vitalPeriodic.csv   7570.53   7.3931
2                         lab.csv   2254.71   2.2019
3             nurseAssessment.csv   2231.54   2.1792
4                intakeOutput.csv   1853.86   1.8104
5                physicalExam.csv   1303.78   1.2732
6         respiratoryCharting.csv   1173.46   1.1460
7                   nurseCare.csv   1129.30   1.1028
8              vitalAperiodic.csv    936.41   0.9145
9                  medication.csv    603.64   0.5895
10                  treatment.csv    322.60   0.3150
11                       note.csv    306.50   0.2993
12              admissionDrug.csv    296.81   0.2899
13                  diagnosis.csv    270.24   0.2639
14               infusionDrug.csv    265.74   0.2595
15                pastHistory.csv    194.20   0.1896
16            carePlanGeneral.csv    177.50   0.1733
17                    allergy.csv    119.80   0.1170
18                admissionDx.csv     88.14   0.0861
19            respiratoryCare.csv     77.37   0.0756
20        apachePatientResult.csv     49.33   0.0482
21                    patient.csv     46.04   0.0450
22               carePlanGoal.csv     35.63   0.0348
23       carePlanCareProvider.csv     26.58   0.0260
24              apachePredVar.csv     21.27   0.0208
25               apacheApsVar.csv     15.11   0.0148
26                   microLab.csv      1.12   0.0011
27  carePlanInfectiousDisease.csv      0.47   0.0005
28                  customLab.csv      0.07   0.0001
29                carePlanEOL.csv      0.04   0.0000
30                   hospital.csv      0.00   0.0000

#### Explanation :
This section sorts the eICU tables from largest to smallest.

Large tables such as periodic vital signs can require more memory and processing time during later analysis.

### Calculate the Total Size of the Processed Data

In [25]:
total_size_bytes = file_size_summary_df["size_bytes"].sum()
total_size_mb = total_size_bytes / (1024 ** 2)
total_size_gb = total_size_bytes / (1024 ** 3)

print("=" * 70)
print("PROCESSED DATA SIZE")
print("=" * 70)
print(f"Total processed files : {len(file_size_summary_df)}")
print(f"Total size in bytes   : {total_size_bytes:,}")
print(f"Total size in MB      : {total_size_mb:,.2f} MB")
print(f"Total size in GB      : {total_size_gb:,.2f} GB")
print("=" * 70)

======================================================================
PROCESSED DATA SIZE
======================================================================
Total processed files : 31
Total size in bytes   : 33,876,002,241
Total size in MB      : 32,306.67 MB
Total size in GB      : 31.55 GB
======================================================================

#### Explanation :
This cell calculates the combined storage size of all CSV files in data/processed/.

It provides a clear estimate of the total processed dataset size.

### Perform the Final Validation

In [26]:
conversion_is_complete = (
    failed_count == 0
    and len(missing_csv_files) == 0
    and len(column_read_errors) == 0
)

print("=" * 70)
print("FINAL VALIDATION")
print("=" * 70)

if conversion_is_complete:
    print("Raw-to-processed conversion completed successfully.")
    print("Every raw file has a matching processed CSV file.")
    print("All processed CSV headers were read successfully.")
else:
    print("The conversion requires attention.")

    if failed_count > 0:
        print(f"- Failed conversions: {failed_count}")

    if missing_csv_files:
        print(f"- Missing processed CSV files: {len(missing_csv_files)}")

    if column_read_errors:
        print(f"- Unreadable CSV headers: {len(column_read_errors)}")

print("=" * 70)

======================================================================
FINAL VALIDATION
======================================================================
Raw-to-processed conversion completed successfully.
Every raw file has a matching processed CSV file.
All processed CSV headers were read successfully.
======================================================================

#### Explanation :

The notebook reports a successful conversion only when:

- No conversion failed.
- Every raw .csv.gz file has a matching .csv file.
- Every processed CSV header can be read.

This final check confirms that the processed eICU tables are ready for the next stage of the project.